#!/bin/bash

# Aceternity Automation Package Installer
# Usage: ./install.sh /path/to/your-project

set -e

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}🚀 Aceternity Automation Package Installer${NC}"
echo ""

# Check if target directory provided
if [ -z "$1" ]; then
    echo -e "${YELLOW}Usage: ./install.sh /path/to/your-project${NC}"
    exit 1
fi

TARGET_DIR="$1"

if [ ! -d "$TARGET_DIR" ]; then
    echo -e "${YELLOW}❌ Directory not found: $TARGET_DIR${NC}"
    exit 1
fi

echo -e "${GREEN}📁 Target directory: $TARGET_DIR${NC}"
echo ""

# Step 1: Copy scripts
echo -e "${BLUE}📝 Step 1: Copying automation scripts...${NC}"
mkdir -p "$TARGET_DIR/scripts"
cp aceternity-fetch.ts "$TARGET_DIR/scripts/"
cp aceternity-auto-integrate.ts "$TARGET_DIR/scripts/"
cp scaffold-aceternity-component.ts "$TARGET_DIR/scripts/"
echo -e "${GREEN}✅ Scripts copied${NC}"
echo ""

# Step 2: Copy documentation
echo -e "${BLUE}📚 Step 2: Copying documentation...${NC}"
cp ACETERNITY-*.md "$TARGET_DIR/" 2>/dev/null || echo "No docs found (optional)"
echo -e "${GREEN}✅ Documentation copied${NC}"
echo ""

# Step 3: Create directory structure
echo -e "${BLUE}📂 Step 3: Creating directory structure...${NC}"
mkdir -p "$TARGET_DIR/components/aceternity/animations"
mkdir -p "$TARGET_DIR/components/aceternity/cards"
mkdir -p "$TARGET_DIR/components/aceternity/backgrounds"
mkdir -p "$TARGET_DIR/components/blocks/aceternity"
mkdir -p "$TARGET_DIR/sanity/schemas/blocks/aceternity"
echo -e "${GREEN}✅ Directories created${NC}"
echo ""

# Step 4: Create README files
echo -e "${BLUE}📄 Step 4: Creating README files...${NC}"
cat > "$TARGET_DIR/components/aceternity/README.md" << 'EOF'
# Aceternity Components

This directory contains Aceternity UI Pro components.

## Structure
- `animations/` - Animation effects (sparkles, particles, etc.)
- `cards/` - Card components (evervault-card, hover-card, etc.)
- `backgrounds/` - Background effects (parallax, grids, etc.)

## Adding New Components

Use automation:
```bash
npm run aceternity:integrate -- [component-name] "Title" "Description" Icon category
```

See project root for ACETERNITY-*.md documentation.
EOF

cat > "$TARGET_DIR/components/blocks/aceternity/README.md" << 'EOF'
# Aceternity Block Wrappers

This directory contains Sanity CMS block wrappers for Aceternity components.

Each wrapper connects:
- Aceternity component (from components/aceternity/)
- Sanity schema (from sanity/schemas/blocks/aceternity/)

Auto-generated by: `npm run aceternity:integrate`
EOF

cat > "$TARGET_DIR/sanity/schemas/blocks/aceternity/README.md" << 'EOF'
# Aceternity Sanity Schemas

This directory contains Sanity CMS schema definitions for Aceternity blocks.

Auto-generated by: `npm run aceternity:integrate`

Each schema defines:
- Field types (text, number, color, etc.)
- Field groups (content, settings, style)
- Validation rules
- Preview configuration
EOF

echo -e "${GREEN}✅ README files created${NC}"
echo ""

# Final instructions
echo -e "${GREEN}✨ Installation complete!${NC}"
echo ""
echo -e "${BLUE}📋 Next Steps:${NC}"
echo ""
echo "1. Add to package.json scripts:"
echo -e "${YELLOW}"
cat << 'EOF'
{
  "scripts": {
    "aceternity:fetch": "tsx scripts/aceternity-fetch.ts",
    "aceternity:integrate": "tsx scripts/aceternity-auto-integrate.ts",
    "scaffold:aceternity": "tsx scripts/scaffold-aceternity-component.ts"
  }
}
EOF
echo -e "${NC}"

echo "2. Add to .env.local:"
echo -e "${YELLOW}"
echo "ACETERNITY_API_KEY=your_api_key"
echo "ANTHROPIC_API_KEY=your_claude_key_optional"
echo -e "${NC}"

echo "3. Install dependencies:"
echo -e "${YELLOW}"
echo "npm install -D tsx"
echo "npm install motion clsx tailwind-merge"
echo -e "${NC}"

echo "4. Test the automation:"
echo -e "${YELLOW}"
echo "npm run aceternity:integrate -- evervault-card \"Evervault Card\" \"Hover effect card\" CreditCard cards"
echo -e "${NC}"

echo ""
echo -e "${GREEN}🎉 Ready to use! Check ACETERNITY-QUICKSTART-AUTOMATION.md for usage examples.${NC}"
