@echo off
REM Aceternity Automation Package Installer (Windows)
REM Usage: install.bat C:\path\to\your-project

echo.
echo ================================
echo Aceternity Automation Installer
echo ================================
echo.

if "%~1"=="" (
    echo Usage: install.bat C:\path\to\your-project
    exit /b 1
)

set TARGET_DIR=%~1

if not exist "%TARGET_DIR%" (
    echo Error: Directory not found: %TARGET_DIR%
    exit /b 1
)

echo Target directory: %TARGET_DIR%
echo.

REM Step 1: Copy scripts
echo [1/4] Copying automation scripts...
if not exist "%TARGET_DIR%\scripts" mkdir "%TARGET_DIR%\scripts"
copy /Y aceternity-fetch.ts "%TARGET_DIR%\scripts\" >nul
copy /Y aceternity-auto-integrate.ts "%TARGET_DIR%\scripts\" >nul
copy /Y scaffold-aceternity-component.ts "%TARGET_DIR%\scripts\" >nul
echo Done.
echo.

REM Step 2: Copy documentation
echo [2/4] Copying documentation...
copy /Y ACETERNITY-*.md "%TARGET_DIR%\" >nul 2>&1
echo Done.
echo.

REM Step 3: Create directory structure
echo [3/4] Creating directory structure...
if not exist "%TARGET_DIR%\components\aceternity\animations" mkdir "%TARGET_DIR%\components\aceternity\animations"
if not exist "%TARGET_DIR%\components\aceternity\cards" mkdir "%TARGET_DIR%\components\aceternity\cards"
if not exist "%TARGET_DIR%\components\aceternity\backgrounds" mkdir "%TARGET_DIR%\components\aceternity\backgrounds"
if not exist "%TARGET_DIR%\components\blocks\aceternity" mkdir "%TARGET_DIR%\components\blocks\aceternity"
if not exist "%TARGET_DIR%\sanity\schemas\blocks\aceternity" mkdir "%TARGET_DIR%\sanity\schemas\blocks\aceternity"
echo Done.
echo.

REM Step 4: Create README files
echo [4/4] Creating README files...
(
echo # Aceternity Components
echo.
echo Auto-generated components from Aceternity UI Pro.
echo Use: npm run aceternity:integrate
) > "%TARGET_DIR%\components\aceternity\README.md"

(
echo # Aceternity Block Wrappers
echo.
echo Sanity CMS wrappers for Aceternity components.
echo Auto-generated by aceternity:integrate script.
) > "%TARGET_DIR%\components\blocks\aceternity\README.md"

(
echo # Aceternity Sanity Schemas
echo.
echo CMS schema definitions for Aceternity blocks.
echo Auto-generated by aceternity:integrate script.
) > "%TARGET_DIR%\sanity\schemas\blocks\aceternity\README.md"

echo Done.
echo.

echo ================================
echo Installation Complete!
echo ================================
echo.
echo Next Steps:
echo.
echo 1. Add to package.json:
echo    "scripts": {
echo      "aceternity:fetch": "tsx scripts/aceternity-fetch.ts",
echo      "aceternity:integrate": "tsx scripts/aceternity-auto-integrate.ts",
echo      "scaffold:aceternity": "tsx scripts/scaffold-aceternity-component.ts"
echo    }
echo.
echo 2. Add to .env.local:
echo    ACETERNITY_API_KEY=your_api_key
echo    ANTHROPIC_API_KEY=your_claude_key
echo.
echo 3. Install dependencies:
echo    npm install -D tsx
echo    npm install motion clsx tailwind-merge
echo.
echo 4. Test:
echo    npm run aceternity:integrate -- evervault-card "Card" "Effect" Icon cards
echo.
echo Ready to use! Check ACETERNITY-QUICKSTART-AUTOMATION.md
echo.
pause
